#-------------------------------
# General Site Settings
title: 
logo:  # You can add own logo.
description: A Blog to document my journey at the fablab, Waag


#-------------------------------
# Author Settings
author:
  name: Farah Hijazi
  image: 
  say-hello: Hello, I'm <strong>Farah Hijazi</strong> 
  bio: A curious person with a background in <strong>Media Art Analysis</strong>, <strong>Design</strong> <strong>& Research</strong>. Currently an intern at Fablab, Waag in Amsterdam. Loves <a href="#">painting</a>, playing music & yoga.


#-------------------------------
# Contact links
twitter: https://twitter.com/ # Add your Twitter handle
facebook: https://facebook.com/ # Add your Facebook handle
dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/ # Add your Instagram handle
pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier:  # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile:  # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
